AllCops:
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - ./*.gemspec

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
